[2025-06-26T21:28:57.715+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-26T21:28:53.925677+00:00 [queued]>
[2025-06-26T21:28:57.741+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-26T21:28:53.925677+00:00 [queued]>
[2025-06-26T21:28:57.743+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-26T21:28:57.772+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-26 21:28:53.925677+00:00
[2025-06-26T21:28:57.788+0000] {standard_task_runner.py:60} INFO - Started process 7391 to run task
[2025-06-26T21:28:57.794+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cards_etl', 'etl_cards_task', 'manual__2025-06-26T21:28:53.925677+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl_cards_dag.py', '--cfg-path', '/tmp/tmp7va6gmkq']
[2025-06-26T21:28:57.800+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask etl_cards_task
[2025-06-26T21:28:57.914+0000] {task_command.py:423} INFO - Running <TaskInstance: cards_etl.etl_cards_task manual__2025-06-26T21:28:53.925677+00:00 [running]> on host 65da94c758f2
[2025-06-26T21:28:59.817+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='cards_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T21:28:53.925677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T21:28:53.925677+00:00'
[2025-06-26T21:28:59.819+0000] {etl_cards_dag.py:22} INFO - Starting ETL for cards
[2025-06-26T21:28:59.886+0000] {ETL_dim_card.py:21} INFO - âœ… Extracted cards_data.csv with 6146 records
[2025-06-26T21:28:59.887+0000] {ETL_dim_card.py:36} INFO - Starting transformation of CARDS data.
[2025-06-26T21:28:59.967+0000] {ETL_dim_card.py:58} INFO - Removed columns ['client_id', 'card_number', 'cvv'] from CARDS data.
[2025-06-26T21:28:59.969+0000] {ETL_dim_card.py:59} INFO - finished transformation of CARDS data.
[2025-06-26T21:28:59.983+0000] {load_data.py:34} INFO - Successfully created database connection engine.
[2025-06-26T21:28:59.985+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_cards_dag.py", line 26, in my_etl_task
    load.load_dataframe_to_sql(cards_df_clean,'dim_card',engine,'financial')
TypeError: load_dataframe_to_sql() missing 2 required positional arguments: 'if_exists' and 'index'
[2025-06-26T21:29:00.013+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cards_etl, task_id=etl_cards_task, execution_date=20250626T212853, start_date=20250626T212857, end_date=20250626T212900
[2025-06-26T21:29:00.075+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task etl_cards_task (load_dataframe_to_sql() missing 2 required positional arguments: 'if_exists' and 'index'; 7391)
[2025-06-26T21:29:00.148+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-26T21:29:00.185+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
