[2025-06-25T11:47:02.987+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-25T11:47:01.740946+00:00 [queued]>
[2025-06-25T11:47:03.001+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cards_etl.etl_cards_task manual__2025-06-25T11:47:01.740946+00:00 [queued]>
[2025-06-25T11:47:03.002+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-25T11:47:03.020+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): etl_cards_task> on 2025-06-25 11:47:01.740946+00:00
[2025-06-25T11:47:03.030+0000] {standard_task_runner.py:60} INFO - Started process 1133 to run task
[2025-06-25T11:47:03.033+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cards_etl', 'etl_cards_task', 'manual__2025-06-25T11:47:01.740946+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/etl_cards_dag.py', '--cfg-path', '/tmp/tmp_eyapsew']
[2025-06-25T11:47:03.037+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask etl_cards_task
[2025-06-25T11:47:03.104+0000] {task_command.py:423} INFO - Running <TaskInstance: cards_etl.etl_cards_task manual__2025-06-25T11:47:01.740946+00:00 [running]> on host 65da94c758f2
[2025-06-25T11:47:03.430+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jimmy' AIRFLOW_CTX_DAG_ID='cards_etl' AIRFLOW_CTX_TASK_ID='etl_cards_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T11:47:01.740946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T11:47:01.740946+00:00'
[2025-06-25T11:47:03.432+0000] {etl_cards_dag.py:21} INFO - Starting ETL for cards
[2025-06-25T11:47:03.468+0000] {extract_data.py:22} INFO - âœ… Extracted cards_data.csv with 6146 records
[2025-06-25T11:47:03.487+0000] {transform_cards.py:72} INFO - Removed columns ['client_id', 'card_number', 'cvv'] from CARDS data.
[2025-06-25T11:47:03.498+0000] {warnings.py:109} WARNING - /opt/***/ETL/transform_cards.py:89: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['expires'] = pd.to_datetime(df['expires'], errors='coerce')

[2025-06-25T11:47:03.501+0000] {transform_cards.py:90} INFO - Set data types for CARDS data.
[2025-06-25T11:47:03.506+0000] {load_data.py:34} INFO - Successfully created database connection engine.
[2025-06-25T11:47:20.435+0000] {load_data.py:81} INFO - Successfully loaded data into table 'financial.dim_card'. 6146 rows and 10 columns
[2025-06-25T11:47:20.436+0000] {etl_cards_dag.py:27} INFO - Finished ETL for cards
[2025-06-25T11:47:20.437+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-25T11:47:20.452+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cards_etl, task_id=etl_cards_task, execution_date=20250625T114701, start_date=20250625T114702, end_date=20250625T114720
[2025-06-25T11:47:20.508+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-25T11:47:20.534+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
